# 创建学生表
DROP TABLE IF EXISTS StudentTable;
CREATE TABLE StudentTable(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  StuId CHAR(20),
  StuName CHAR(20)
);
# 创建书籍信息表
DROP TABLE IF EXISTS BookTable;
CREATE TABLE BookTable(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  BookName CHAR(20) NOT NULL,
  Author CHAR(20) NOT NULL
);
# 借阅信息表
DROP TABLE IF EXISTS BorrowTable;
CREATE TABLE BorrowTable(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  StuId INT NOT NULL,
  StudentNAME CHAR(20),
  BookName CHAR(20),
  Author CHAR(20)
);